# Generated by Django 5.1.4 on 2025-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_blocked_users_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_42',
            field=models.BooleanField(default=False),
        ),
    ]
