# Generated by Django 5.1.4 on 2025-01-16 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueState',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('total_players', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'queue_state',
            },
        ),
        migrations.CreateModel(
            name='QueuePosition',
            fields=[
                ('position', models.IntegerField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue_position',
            },
        ),
    ]
