# Generated by Django 5.1.4 on 2025-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_queuestate_queueposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='movement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
