# Generated by Django 5.1.4 on 2025-02-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
